export const Images = {
  account: require('@app/assets/images/account.png'),
  aspireLogo: require('@app/assets/images/aspire_logo.png'),
  card: require('@app/assets/images/card.png'),
  commerce: require('@app/assets/images/commerce.png'),
  credit: require('@app/assets/images/credit.png'),
  home: require('@app/assets/images/home.png'),
  insight: require('@app/assets/images/insight.png'),
  logo: require('@app/assets/images/logo.png'),
  nature1: require('@app/assets/images/nature_1.png'),
  nature: require('@app/assets/images/nature.png'),
  pay: require('@app/assets/images/pay.png'),
  payments: require('@app/assets/images/payments.png'),
  pickupCar: require('@app/assets/images/pickup_car.png'),
  eye: require('@app/assets/images/eye.png'),
  hideEye: require('@app/assets/images/hide_eye.png'),
  symbol: require('@app/assets/images/symbol.png'),
  transfer: require('@app/assets/images/transfer.png'),
  transfer1: require('@app/assets/images/transfer_1.png'),
  transfer2: require('@app/assets/images/transfer_2.png'),
  transfer3: require('@app/assets/images/transfer_3.png'),
  user: require('@app/assets/images/user.png'),
  visa: require('@app/assets/images/visa.png'),
  back: require('@app/assets/images/back.png'),
};
